### ISSUE TITLE
编译文件去哪里了？

### ISSUE THREAD

**Issue by lshilshi** [wenhelinlu/spark#7]
试着用actions来CI
相关段为
```
 - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            app/**/apk/release/*
            app/**/mapping/release/mapping.txt
```

看build的反馈信息
```
BUILD SUCCESSFUL in 2m 30s
36 actionable tasks: 36 executed
```

upload的信息是
```
With the provided path, there will be 2 files uploaded
Total size of all the files uploaded is 8130598 bytes
Finished uploading artifact artifacts. Reported size is 8130598 bytes. There were 0 items that failed to upload
Artifact artifacts has been successfully uploaded!
```

结果在repo底下，或者jitpack.io都找不到编译文件，它们去哪里了？
